# Generated by Django 4.0.5 on 2022-06-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_compound', models.TextField()),
                ('product_price', models.CharField(max_length=20)),
                ('product_image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
